"""Writing OpenSpace `.asset` scene configuration.

An .asset file is a Lua table describing scene graph nodes.  We only ever
*write* Lua as text -- nothing here parses or executes it.

Two renderables are produced:

  * one RenderableSphere per mapped star, carrying its B_r texture, translated
    to the star's true ICRS position and tilted by its rotation-axis
    inclination;
  * one point cloud for the surrounding cluster membership.
"""

import numpy as np

from .io import PARSEC_M, RSUN_M

# ---------------------------------------------------------------------------
# The point-cloud renderable was renamed in OpenSpace 0.20: the older
# `RenderableBillboardsCloud` became `RenderablePointCloud`, and its property
# groups were reorganised at the same time (flat `ScaleExponent` / `ColorMap`
# keys moved under `SizeSettings` / `Coloring`).  We emit the 0.20+ form.  For
# 0.19 or earlier, change this constant *and* flatten those two groups.
POINT_CLOUD_RENDERABLE = "RenderablePointCloud"

# Where these nodes hang in the scene graph, and in the OpenSpace GUI tree.
PARENT_NODE = "SolarSystemBarycenter"
GUI_PATH = "/Milky Way/Hyades ZDI"

# Written into every asset's `meta` block. Update after creating the repo.
AUTHOR = "Federica Chiti"
REPO_URL = "https://github.com/USERNAME/ZDIviz"

# Sphere tessellation.  128 segments keeps the poles clean at dome resolution
# without making the scene heavy; the textures are 2048x1024 regardless.
SPHERE_SEGMENTS = 128


def _header(lines, exaggeration=None):
    """Standard banner.

    When the file actually contains exaggerated radii, the factor is stated
    here -- always, and prominently. The point cloud has no radii to
    exaggerate, so it omits the block rather than claiming a scaling it does
    not apply.
    """
    out = [
        "-- Generated by ZDIviz. Do not edit by hand; edit the builder.",
        "--",
    ] + [("-- " + line).rstrip() for line in lines]
    if exaggeration is not None:
        out += [
            "--",
            f"-- RADIUS EXAGGERATION: {exaggeration:.6g}x",
            "--   Stellar radii are ~1e-8 of interstellar distances, so spheres",
            "--   at true scale are far below one pixel. Every sphere below is",
            f"--   drawn {exaggeration:.6g} times larger than the star actually is.",
            "--   Positions and distances are NOT exaggerated; only the radii.",
        ]
    return out + [""]


def spin_axis_vector(ra_deg, dec_deg, inclination_deg):
    """Unit vector along the star's rotation axis, in ICRS Cartesian.

    Inclination `i` is the angle between the spin axis and the line of sight,
    and it is the one orientation angle ZDI genuinely constrains: it sets which
    pole is visible and how much of the far hemisphere is hidden.  The position
    angle of the axis *on the sky* is not constrained by the technique, so we
    fix it by convention -- the axis leans towards ICRS north.

    With r_hat the unit vector Sun -> star, the axis sits at angle i from the
    direction back to the observer (-r_hat), tilted towards sky-projected north.
    Returns (axis, north_hat); the caller needs both to build a full frame.
    """
    ra, dec, inc = np.radians([ra_deg, dec_deg, inclination_deg])
    r_hat = np.array([np.cos(dec) * np.cos(ra),
                      np.cos(dec) * np.sin(ra),
                      np.sin(dec)])

    # Sky-projected ICRS north: the component of +Z perpendicular to the line
    # of sight.  Degenerate only if the star sits exactly at a celestial pole.
    north = np.array([0.0, 0.0, 1.0]) - r_hat[2] * r_hat
    norm = np.linalg.norm(north)
    north = np.array([1.0, 0.0, 0.0]) if norm < 1e-8 else north / norm

    return np.cos(inc) * (-r_hat) + np.sin(inc) * north, north


def spin_axis_rotation(ra_deg, dec_deg, inclination_deg):
    """Euler angles (XYZ, radians) that tilt a sphere onto its spin axis.

    Same geometry as `spin_axis_vector`, expressed the way OpenSpace's
    StaticRotation wants it.
    """
    axis, north = spin_axis_vector(ra_deg, dec_deg, inclination_deg)

    # Orthonormal frame with the model's +Z (the texture's north pole) on the
    # spin axis.  Columns of R map model coordinates into world coordinates.
    x_col = np.cross(north, axis)
    if np.linalg.norm(x_col) < 1e-8:                        # axis parallel to north
        x_col = np.cross(np.array([1.0, 0.0, 0.0]), axis)
    x_col /= np.linalg.norm(x_col)
    y_col = np.cross(axis, x_col)
    R = np.column_stack([x_col, y_col, axis])

    # Decompose as R = Rx(a) Ry(b) Rz(c), the intrinsic XYZ convention glm --
    # and therefore OpenSpace's StaticRotation -- uses for Euler input.
    b = np.arcsin(np.clip(R[0, 2], -1.0, 1.0))
    a = np.arctan2(-R[1, 2], R[2, 2])
    c = np.arctan2(-R[0, 1], R[0, 0])
    return float(a), float(b), float(c)


def write_star_assets(entries, out_dir, exaggeration):
    """Write `zdi_stars.asset`: one RenderableSphere per mapped star.

    `entries` is a list of (target dict, texture filename, vmax_gauss).
    Translations are in metres, as OpenSpace requires; the .speck uses parsecs.
    """
    lines = _header([
        "One textured sphere per ZDI-mapped star.",
        "Texture = radial field B_r, diverging scale symmetric about zero.",
        "Translation is StaticTranslation in METRES (OpenSpace scene units).",
        f"Parent node: {PARENT_NODE}.",
    ], exaggeration)

    lines.append("local nodes = {")
    for target, texture_name, vmax in entries:
        pos_m = [target[k] * PARSEC_M for k in ("x_pc", "y_pc", "z_pc")]
        radius_m = target["radius_rsun"] * RSUN_M * exaggeration
        rx, ry, rz = spin_axis_rotation(
            target["ra_deg"], target["dec_deg"], target["inclination_deg"] or 90.0)

        ident = f"ZDI_{target['slug']}_{target['epoch']}"
        lines += [
            f"  -- {target['name']}  epoch {target['epoch']}"
            f"  |  d = {target['dist_pc']:.2f} pc"
            f"  |  R = {target['radius_rsun']:.3f} Rsun"
            f"  |  i = {target['inclination_deg']:.1f} deg"
            f"  |  max|Br| = {vmax:.1f} G",
            "  {",
            f'    Identifier = "{ident}",',
            f'    Parent = "{PARENT_NODE}",',
            "    Transform = {",
            "      Translation = {",
            '        Type = "StaticTranslation",',
            "        Position = { %.6e, %.6e, %.6e }" % tuple(pos_m),
            "      },",
            "      Rotation = {",
            '        Type = "StaticRotation",',
            "        -- Euler XYZ in radians; tilts the pole to inclination"
            f" i = {target['inclination_deg']:.1f} deg",
            "        Rotation = { %.6f, %.6f, %.6f }" % (rx, ry, rz),
            "      }",
            "    },",
            "    Renderable = {",
            '      Type = "RenderableSphere",',
            "      Enabled = true,",
            f"      -- {target['radius_rsun']:.4f} Rsun x {exaggeration:.6g} exaggeration",
            "      Size = %.6e," % radius_m,
            f"      Segments = {SPHERE_SEGMENTS},",
            f'      Texture = asset.resource("textures/{texture_name}"),',
            '      Orientation = "Outside",',
            "      Opacity = 1.0,",
            "      MirrorTexture = false",
            "    },",
            "    GUI = {",
            f'      Name = "{target["name"]} ({target["epoch"]}) B_r",',
            f'      Path = "{GUI_PATH}"',
            "    }",
            "  },",
        ]
    lines += ["}", ""] + _lifecycle() + _meta(
        "Hyades ZDI Surface Maps",
        "Zeeman-Doppler Imaging radial-field maps rendered on spheres at Gaia positions.")

    path = out_dir / "zdi_stars.asset"
    path.write_text("\n".join(lines) + "\n")
    return path


def write_cloud_asset(out_dir, n_points, prot_range):
    """Write `hyades_cloud.asset`: the cluster membership as a point cloud."""
    lo, hi = prot_range
    lines = _header([
        f"Hyades ZDI sample as a point cloud ({n_points} stars).",
        "Positions read from hyades.speck, in PARSECS (Unit = 'pc').",
        f"Colour maps the 'prot' datavar (rotation period, {lo:.2f}-{hi:.2f} d).",
        "The 'hasmap' datavar flags stars that have a surface map in this build.",
        "",
        "These are screen-space points, not scaled spheres: no radius, and so",
        "no radius exaggeration. Point size is a display setting, not a size.",
    ])

    lines += [
        "local node = {",
        '  Identifier = "HyadesZDICloud",',
        f'  Parent = "{PARENT_NODE}",',
        "  Renderable = {",
        f'    Type = "{POINT_CLOUD_RENDERABLE}",',
        "    Enabled = true,",
        '    File = asset.resource("hyades.speck"),',
        '    Unit = "pc",',
        "    Coloring = {",
        "      ColorMapping = {",
        '        File = asset.resource("prot.cmap"),',
        '        ParameterOptions = { { Key = "prot", Range = { %.3f, %.3f } } }'
        % (lo, hi),
        "      }",
        "    },",
        "    SizeSettings = {",
        "      ScaleExponent = 16.5,",
        "      MaxSize = 3.0,",
        "      EnableMaxSizeControl = true",
        "    },",
        "    Labels = {",
        '      File = asset.resource("hyades.label"),',
        "      Color = { 0.6, 0.7, 0.85 },",
        "      Size = 15.0,",
        "      Enabled = false",
        "    },",
        "    Opacity = 1.0",
        "  },",
        "  GUI = {",
        '    Name = "Hyades ZDI Sample",',
        f'    Path = "{GUI_PATH}"',
        "  }",
        "}",
        "",
        "local nodes = { node }",
        "",
    ] + _lifecycle() + _meta(
        "Hyades ZDI Sample Point Cloud",
        "Cluster membership of the ZDI sample, coloured by rotation period.")

    path = out_dir / "hyades_cloud.asset"
    path.write_text("\n".join(lines) + "\n")
    return path


def _lifecycle():
    """The add/remove boilerplate every OpenSpace asset needs."""
    return [
        "asset.onInitialize(function()",
        "  for _, n in ipairs(nodes) do",
        "    openspace.addSceneGraphNode(n)",
        "  end",
        "end)",
        "",
        "asset.onDeinitialize(function()",
        "  for i = #nodes, 1, -1 do",
        "    openspace.removeSceneGraphNode(nodes[i].Identifier)",
        "  end",
        "end)",
        "",
        'asset.export("nodes", nodes)',
        "",
    ]


def _meta(name, description):
    return [
        "asset.meta = {",
        f'  Name = "{name}",',
        '  Version = "1.0",',
        f'  Description = "{description}",',
        f'  Author = "{AUTHOR}",',
        f'  URL = "{REPO_URL}",',
        '  License = "MIT"',
        "}",
    ]
