"""Writing the Digital Universe `.speck` point catalogue.

A .speck file is plain text with two parts:

    datavar <index> <name>          header, declares one column per variable
    x y z <var0> <var1> ... # label   one line per point, positions in parsecs

Column order in the data lines must match the datavar indices, which start at
0 and refer to the fields *after* x/y/z.  The trailing `# label` is what
OpenSpace draws next to the point.  That is the whole format; nothing is
compiled and nothing is executed.
"""

# Declared once, used for both the header and the row writer, so the two can
# never fall out of step.  (key in the target dict, datavar name, format)
DATAVARS = [
    ("prot_d",          "prot",        "%.3f"),   # rotation period, days
    ("radius_rsun",     "radius",      "%.4f"),   # stellar radius, solar radii
    ("teff_k",          "teff",        "%.1f"),   # effective temperature, K
    ("inclination_deg", "inclination", "%.2f"),   # rotation-axis inclination, deg
    ("dist_pc",         "distance",    "%.3f"),   # distance, parsecs
]

# Sentinel for an absent optional value.  Digital Universe catalogues use a
# large negative number rather than a blank, since the format has no NaN.
MISSING = -999.0


def write_speck(targets, path, mapped_keys=()):
    """Write `targets` as a .speck point catalogue in parsecs.

    `mapped_keys` is the set of (star, epoch) tuples that have a ZDI map; those
    get an extra `hasmap` flag so the cluster can be colour- or size-coded to
    distinguish mapped stars from the surrounding membership.
    """
    mapped_stars = {star for star, _ in mapped_keys}

    lines = [
        "# Hyades ZDI sample - one point per star, ICRS Cartesian, parsecs",
        "# Generated by ZDIviz; positions from Gaia parallax (d = 1000/plx).",
        "#",
    ]
    for i, (_, name, _) in enumerate(DATAVARS):
        lines.append(f"datavar {i} {name}")
    lines.append(f"datavar {len(DATAVARS)} hasmap")
    lines.append("")

    for t in targets:
        cols = []
        for key, _, fmt in DATAVARS:
            value = t.get(key)
            cols.append(fmt % (MISSING if value is None else value))
        cols.append("1" if t["star"] in mapped_stars else "0")
        lines.append("%.6f %.6f %.6f %s # %s"
                     % (t["x_pc"], t["y_pc"], t["z_pc"], " ".join(cols), t["name"]))

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return len(targets)


def write_label(targets, path):
    """Write the companion `.label` file.

    Same geometry as the .speck but carrying only text:
        x y z text <label>
    OpenSpace keeps labels in a separate file from the points so they can be
    toggled and styled independently.
    """
    lines = ["# Labels for the Hyades ZDI sample, ICRS Cartesian, parsecs",
             "textcolor 1", ""]
    for t in targets:
        lines.append("%.6f %.6f %.6f text %s"
                     % (t["x_pc"], t["y_pc"], t["z_pc"], t["name"]))
    path.write_text("\n".join(lines) + "\n")
    return len(targets)


def write_cmap(path, stops):
    """Write a Digital Universe `.cmap` colour table.

    Format is a bare count followed by that many `r g b a` lines in 0-1.
    `stops` is a list of (r, g, b) floats; the point cloud interpolates
    between them across the mapped parameter's range.
    """
    lines = [str(len(stops))]
    lines += ["%.4f %.4f %.4f 1.0" % tuple(s) for s in stops]
    path.write_text("\n".join(lines) + "\n")
    return len(stops)
